# Project: Node
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = testCase.o
LINKOBJ  = testCase.o
LIBS     = -L"D:/App/DEVC/Dev-Cpp/TDM-GCC-64/lib" -L"D:/App/DEVC/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/App/DEVC/Dev-Cpp/TDM-GCC-64/include" -I"D:/App/DEVC/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/App/DEVC/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/App/DEVC/Dev-Cpp/TDM-GCC-64/include" -I"D:/App/DEVC/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/App/DEVC/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/App/DEVC/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = Node.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
DEL      = D:\App\DEVC\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

testCase.o: testCase.cpp
	$(CPP) -c testCase.cpp -o testCase.o $(CXXFLAGS)
